language: python
python:
  - "3.9"
# command to install dependencies
before-install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install
# command to run tests
script:
  - coverage run --source=src -m pytest tests/
  - coveralls
  - mutmut run --simple-output
  - flake8 .
  - bandit -c pyproject.toml -r -q .
  - safety check
  - mypy -p src
  - mypy -p tests
