language: python
python:
  - "3.9"
# command to install dependencies
before-install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install
# command to run tests
script:
  - pytest
